[workspace]
resolver = "2"
members = ["crates/rutis", "crates/rutis-agent"]

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT"

[workspace.dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros", "time"] }
tokio-util = { version = "0.7", features = ["rt"] }
thiserror = "2"
